//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reddit_Clone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int comment_id { get; set; }
        public Nullable<int> parent_comment_id { get; set; }
        public Nullable<int> post_id { get; set; }
        public string author { get; set; }
        public Nullable<int> upvotes { get; set; }
        public Nullable<int> downvotes { get; set; }
        public byte[] creation_time { get; set; }
        public bool edit_flag { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
