//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reddit_Clone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int post_id { get; set; }
        public string username { get; set; }
        public string subreddit_name { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> upvotes { get; set; }
        public Nullable<int> downvotes { get; set; }
        public Nullable<bool> edit_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Subreddit Subreddit { get; set; }
        public virtual User User { get; set; }
    }
}
